# Generated by Django 2.2.3 on 2020-02-12 06:54

from django.db import migrations, models
import django.db.models.deletion
import pika.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20200212_0654'),
        ('base', '0001_initial'),
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participation',
        ),
        migrations.CreateModel(
            name='MovieParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(blank=True, max_length=64, null=True, verbose_name='Character')),
                ('rus_character', models.CharField(blank=True, max_length=64, null=True, verbose_name='Character in russian')),
                ('gender', pika.db.fields.GenderField(blank=True, choices=[(0, 'unknown'), (1, 'Female'), (2, 'Male')], null=True, verbose_name='Gender')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Job', verbose_name='Job')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='movie.Movie', verbose_name='Movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='person.Person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Participation',
                'verbose_name_plural': 'Participation',
                'db_table': 'movie_participation',
            },
        ),
    ]
