# Generated by Django 2.2.3 on 2020-02-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Rumored'), (2, 'Planned'), (3, 'In production'), (4, 'Post production'), (5, 'Released'), (6, 'Cancelled')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='movievideo',
            name='size',
            field=models.IntegerField(default=-1, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='movievideo',
            name='type',
            field=models.IntegerField(choices=[(0, 'Other'), (1, 'Trailer'), (2, 'Teaser'), (3, 'Clip'), (4, 'Featurette'), (5, 'Behind the Scenes'), (6, 'Bloopers')], default=6, verbose_name='Type'),
        ),
    ]
