# Generated by Django 2.2.3 on 2020-02-17 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20200217_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieparticipant',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='person.Person', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='content',
            field=models.TextField(default='', verbose_name='Text'),
        ),
    ]
