# Generated by Django 2.2.3 on 2020-02-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20200212_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviebackdrop',
            name='vote_average',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Vote average'),
        ),
        migrations.AlterField(
            model_name='movieposter',
            name='vote_average',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Vote average'),
        ),
    ]
