# Generated by Django 2.2.3 on 2020-02-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20200214_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviebackdrop',
            name='path',
            field=models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Path'),
        ),
        migrations.AlterField(
            model_name='movieposter',
            name='path',
            field=models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Path'),
        ),
    ]
