# Generated by Django 2.2.3 on 2020-02-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_auto_20200217_0652'),
        ('base', '0001_initial'),
        ('movie', '0004_auto_20200214_1249'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieParticipation',
            new_name='MovieParticipant',
        ),
        migrations.AlterModelOptions(
            name='movieparticipant',
            options={'verbose_name': 'Movie participant', 'verbose_name_plural': 'Movie participants'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='adult',
            field=models.BooleanField(default=False, verbose_name='Adult'),
        ),
        migrations.AlterModelTable(
            name='movieparticipant',
            table='movie_participant',
        ),
    ]
