# Generated by Django 2.2.3 on 2020-02-20 06:09

from django.db import migrations, models
import pika.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20200217_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieposter',
            name='movie',
        ),
        migrations.RenameField(
            model_name='movieparticipant',
            old_name='gender',
            new_name='character_gender',
        ),
        migrations.AddField(
            model_name='movie',
            name='rus_backdrop',
            field=pika.db.fields.BackdropImageField(blank=True, max_length=64, null=True, verbose_name='Russian backdrop'),
        ),
        migrations.AddField(
            model_name='movie',
            name='rus_poster',
            field=pika.db.fields.PosterImageField(blank=True, max_length=64, null=True, verbose_name='Russian poster'),
        ),
        migrations.AddField(
            model_name='movieparticipant',
            name='tmdb_cast_id',
            field=models.CharField(default='', max_length=32, verbose_name='TMDB cast ID'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MovieBackdrop',
        ),
        migrations.DeleteModel(
            name='MoviePoster',
        ),
    ]
