# Generated by Django 2.2.3 on 2020-02-20 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20200220_0705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieparticipant',
            name='character_gender',
        ),
    ]
