# Generated by Django 2.2.3 on 2020-02-12 06:54

from django.db import migrations
import pika.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=pika.db.fields.GenderField(blank=True, choices=[(0, 'unknown'), (1, 'Female'), (2, 'Male')], null=True, verbose_name='Gender'),
        ),
    ]
