# Generated by Django 2.2.3 on 2020-02-26 19:23

from django.db import migrations
import pika.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='imdb_id',
            field=pika.db.fields.IMDBId(blank=True, db_index=True, max_length=9, null=True, verbose_name='IMDB Id'),
        ),
    ]
