# Generated by Django 2.2.3 on 2020-02-20 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonTMDBImage',
        ),
    ]
