# Generated by Django 2.2.3 on 2020-02-26 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20200226_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='person',
            name='rus_biography',
        ),
    ]
