# Generated by Django 2.2.3 on 2020-02-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_auto_20200214_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='adult',
            field=models.BooleanField(default=False, verbose_name='Adult'),
        ),
        migrations.AlterField(
            model_name='person',
            name='popularity',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=6, verbose_name='Popularity'),
        ),
    ]
