# Generated by Django 2.2.3 on 2020-02-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_auto_20200217_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persontmdbimage',
            name='aspect_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Aspect ratio'),
        ),
        migrations.AlterField(
            model_name='persontmdbimage',
            name='height',
            field=models.IntegerField(default=-1, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='persontmdbimage',
            name='vote_average',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Vote average'),
        ),
        migrations.AlterField(
            model_name='persontmdbimage',
            name='vote_count',
            field=models.IntegerField(default=0, verbose_name='Vote count'),
        ),
        migrations.AlterField(
            model_name='persontmdbimage',
            name='width',
            field=models.IntegerField(default=-1, verbose_name='Width'),
        ),
    ]
