version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=pika
      - POSTGRES_PASSWORD=pika
      - POSTGRES_DB=pika
      - PGPASSWORD=pika
    volumes:
      - "pika_postgres_data:/var/lib/postgresql/data"
    ports:
    - "5432:5432"

  django:
    build: .
    volumes:
      - ./src:/code/src
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db

volumes:
  pika_postgres_data: