version: '2'

services:
    rabbit:
        hostname: rabbitmq
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=admin
            - RABBITMQ_DEFAULT_VHOST=grass
        ports:
            - "5672:5672"

    worker:
        build:
            context: .
        volumes:
            - ./src:/grass/src
        links:
            - rabbit
        depends_on:
            - rabbit
