version: '2'

services:
  rabbit:
    hostname: rabbitmq
    image: rabbitmq:3.8-rc-management
    network_mode: "host"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_VHOST=grass
    ports:
      - "5672:5672"

  worker:
    build:
      context: .
    network_mode: "host"
    environment:
      - PIKA_URL=http://127.0.0.1:8000
      - PIKA_USERNAME=admin
      - PIKA_PASSWORD=admin
      - TMDB_API_KEY=${PIKA_TMDB_API_KEY}
    volumes:
      - ./src:/grass/src
    depends_on:
      - rabbit
    ports:
    - "5555:5555"
