# Generated by Django 2.2.3 on 2020-02-20 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='rus_overview',
        ),
    ]
